#+title: PiCMCA - Part #1
#+date: <2024-10-03 16:51>
#+description: 
#+filetags: electronics linux computer-science engineering


The Pi Compute Module Cardbus Adapter: PiCMCA, is a Cardbus (PCMCIA)
module that uses the USB lanes of the Cardbus interface as a
low-latency network connection between the host system and a Raspberry
Pi compute module system-on-a-chip.

This allows for the host laptop to act as a thin client for the
Raspberry Pi, thus allowing vintage computers to act as modern
computing devices.


* Why?
I am the happy owner of a Thinkpad x61, which is now a grand 14 years
old. It is, of course, beginning to show its age, with its fans loud
as a microwave, and a battery with the lifespan of an elderly mayfly.

For all that, it is still in excellent condition, so I wanted to give
it another chance at life. And I would assume that there are many
others similarly attached to their old computers who could stand to
benefit - not to mention the potential reduction in e-waste.

I then came across the [[https://geoff.greer.fm/2017/07/16/thinkpad-x62/][Thinkpad x62/x63]]: an extreme modification to
the x61 which supplants the original motherboard with an entirely
custom-built motherboard with modern components.

Sadly, these were very expensive, and available for purchase only by
wiring money to various individuals overseas, who would then mail the
motherboard over to you (from anecdotal data, usually taking several
months). And difficulties with customs and legalese etc. make things
really quite dubious.

So, I did the natural thing, and decided to take matters into my own
hands.

* Plan
In the first place, I didn't need the full processing power of a
mobile 5GHz Intel CPU with integrated graphics and a 4K LCD screen -
far from it; I needed only something I could use to browse the web,
comfortably write up some documents, watch some films. And not also
perform a secondary function as a portable stove. So if I could
implant the Pi compute module 4 into the existing internals, that
would be a quite apposite solution.

The Pi would use the Thinkpad SSD for storage using a technology such
as NFS or SSHFS, since the SD card/eMMC is unsuitable for anything
more than the OS. Ideally I'd have the entire root filesystem on the
Thinkpad using PXE/netbooting, but alas my proficiency in wizardry
extends only so far. It might be possible to have the boot partition
on the SD card then mount root as NFS, however this is an optimisation
problem so to be tackled later on.

It is relatively messy to have the files on the client, but unlike in
an OS like Plan9, we can't just set each as CPU server and File
server. I was considering setting up Plan9, but felt that it would
have hindered usability a little too much.

The plan was to design a standard PCB for the Pi CM4 (hence the name
of the project), however I soon came to realise, reading the
specification, that the height of a PCMCIA card is a quite strict
5mm. A Pi CM4 on the other hand, is 4.78mm tall.

So looking into what I could do there, I came across flex PCBs and
extra thin FR4 PCBs, which have a potential depth of less than 0.20mm.

This seemed perfect, however, I could not find any detailed
specification for the depth of the CM4 connector itself that would be
soldered to the PCB, which if too tall would have been very sad
indeed. I did find that the "mounted stacking height" of the connector
would be 1.5mm, however I was unsure if this included the connector on
the CM4 itself - in which case the total height would be 5.11mm...

So I assumed that tolerances wouldn't be /that/ tight and went ahead
anyway.

https://github.com/thagrol/Guides/blob/main/ethernetgadget.pdf


* Proof of Concept
To begin with I used an off-the-shelf carrier board which breaks out
the USB lanes, so that I would be able to test that my software stack
would work in practice, before committing to designing my own using
the Cardbus interface. 

This took some quite extensive configuration, but I managed to make
things work, running [[https://alpinelinux.org/][Alpine Linux]] on both the Pi and the
laptop. Alpine is inherently a very small and efficient operating
system, owing to have been designed for usage in embedded systems.

I initially considered using X-forwarding, however this would have
resulted in needing to run two separate X11 servers, which would have
been pointlessly inefficient.

But eventually what I found was that the solution was in the name -
X11 servers being /servers/, surely meant that I could run the X11
server on the Pi and then use the laptop as solely a client. And this
led me to [[https://wiki.archlinux.org/title/XDMCP][XDMCP]] - a protocol for opening remote X sessions.

So I installed X11 on the Pi, for which Alpine provides a very
convenient =setup-xorg-script=, and set up XDMCP, thus giving me a
fully functional proof of concept.


* Hardware design
** Plan
I was able to use the regular Pi 4B in the proof of concept via USB
gadget mode, which allows one to run the Pi headlessly, using the USB
interface as a network connection to transfer data. In theory, I saw
two paths to mimic this same connection over the Cardbus interface:

1. Bridge Cardbus (PCI) to USB

   I looked at existing Cardbus-USB adapters and found that they all
   seemed to use the same chip: the VT6212/VT6212L. This seemed
   promising, although I was running into space constraints with
   fitting the 20x14mm footprint alongside the CM4.

2. Bridge Cardbus (PCI) to Ethernet

   The cards I found for these seemed distinctly more complex, and I
   found that the gains in bandwidth would be largely redundant for
   the throughput needed by XDMCP ([[https://wiki.ubuntu.com/xdmcp][~100mbit]]), for which even
   USB1.0/Low-Speed should be sufficient (~1.5Mbps). So USB was
   looking much more pleasant to work with.

3. Connect the compute module directly to the Cardbus interface.

   This seemed most efficient, and would be potentially simpler in
   terms of circuit design, but would likely have involved writing
   device drivers. 


The USB route seemed most simple, so I am moving forward with that
plan, but should there be some fatal flaws with e.g size constraints,
I may be forced to consider other options. 

** Design
I've neither designed a PCB nor used ICs before, so I was a little
lost to begin with. I decided to acquire a Cardbus-USB adapter card
that I could open up to reverse engineer.
